#include "nsISupports.idl"
#include "nsISimpleEnumerator.idl"
#include "nsIRDFDataSource.idl"
#include "nsIRDFUtilDataSource.idl"
#include "nsIDOMJSWindow.idl"
[scriptable, uuid(06e87756-c1a8-4f4c-a388-739be1b296c2)]
interface nsIDeliciousBarService : nsISupports
{
	readonly attribute nsIRDFUtilDataSource datasource;
	attribute string username;
	attribute string password;
	
	readonly attribute nsIRDFResource NC_Name;
	readonly attribute nsIRDFResource NC_URL;
	readonly attribute nsIRDFResource NC_BookmarksRoot;
	readonly attribute nsIRDFResource NC_Description;
	readonly attribute nsIRDFResource NC_Bookmark;
	readonly attribute nsIRDFResource NC_Folder;
	readonly attribute nsIRDFResource NC_Icon;
	
	readonly attribute nsIRDFResource WEB_Modified;
	
	readonly attribute nsIRDFResource RDF_Type;
	
	readonly attribute nsIRDFResource DLC_PostRoot;
	readonly attribute nsIRDFResource DLC_TagRoot;
	readonly attribute nsIRDFResource DLC_Tag;
	readonly attribute nsIRDFResource DLC_TagName;

	readonly attribute nsIRDFResource DLBAR_AllTags;
	readonly attribute nsIRDFResource DLBAR_AnyTags;
	readonly attribute nsIRDFResource DLBAR_NoneTags;
	
	nsIRDFResource createFolder(in nsIRDFResource parent);
	void updateFolder(in nsIRDFResource folder);
	void deleteFolder(in nsIRDFResource folder);
	
	nsIRDFResource getBookmark(in string url);
	nsIRDFResource createBookmark(in string url);
	boolean updateBookmark(in nsIRDFResource bookmark);
	boolean deleteBookmark(in nsIRDFResource bookmark);
	void setLocationIcon(in string location, in string faviconurl);
	
	nsISimpleEnumerator getTags(in nsIRDFResource bookmark);
	string getTagsAsString(in nsIRDFResource bookmark);
	void addTag(in nsIRDFResource bookmark, in string tag);
	void removeTag(in nsIRDFResource bookmark, in string tag);
	void setAllTags(in nsIRDFResource bookmark, in string tag);
	void removeAllTags(in nsIRDFResource bookmark);
	
	void clean( );
	void update( );
	
	string URLEncode(in string plaintext);
	string URLDecode(in string encoded);
};
